credit_risk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('loan_admin/', include('loan_admin.urls')),
    path('loan_officer/', include('loan_officer.urls')),
    path('', include('login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
import os

STATIC_ROOT = os.path.join(settings.BASE_DIR, "static/login")

app_name = 'login'
urlpatterns = [
	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('login?add=invalid', views.login, name='login1'),
	path('authenticate_and_redirect', views.authenticate_and_redirect, name='authenticate_and_redirect'),
	path('login/logout', views.logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/models.py
from django.db import models

class Sessions(models.Model):
	user = models.CharField(max_length=10)

	def destroy(self):
		self.user = "None"
		self.save()

login/forms.py
from django import forms
# from bootstrap4.widgets import RadioSelectButtonGroup

class UserForm(forms.Form):
	name = forms.ChoiceField(
			help_text="Select the User",
			required=True,
			label="Select User ",
			# widget=RadioSelectButtonGroup(attrs={'class': 'form-control'}),
			choices=((1, 'Admin'), (2, 'Officer')),
			initial=1,
			)
	password = forms.CharField(label="Password", required=True, 
		widget=forms.PasswordInput(attrs={'class': 'form-control'}))

login/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.urls import reverse
from urllib.parse import urlencode
from django.contrib import messages
from .models import Sessions

def index(request):
	return render(request, 'login/index.html')

def login(request):
	add = request.GET.get('add')
	form = UserForm()
	session = Sessions.objects.all().first()
	if(session.user == "1"):
		return redirect('loan_admin:index')
	if(session.user == "2"):
		return redirect('loan_officer:index')
	if(add):
		messages.info(request, 'Password incorrect')
	context = {'form':form}
	return render(request, 'login/login.html', context)

@require_POST
def authenticate_and_redirect(request):
	arr = ['', 'Admin', 'Officer']
	print(request.POST)
	user = authenticate(username=arr[int(request.POST['name'])], password=request.POST['password'])
	if user is not None:
		name = request.POST['name']
		ins = Sessions.objects.all().first()
		if(ins is None):
			new = Sessions(user=name)
			new.save()
		else:
			ins.user = name
			ins.save()
		if name is '1':
			return redirect(reverse('loan_admin:index'))
		if name is '2':
			return redirect('loan_officer:index')
	else:
		base_url = reverse('login:login')
		query_string =  urlencode({'add': 'invalid'})
		url = '{}?{}'.format(base_url, query_string)
		return redirect(url)

def logout(request):
	ins = Sessions.objects.all().first()
	ins.user = "None"
	ins.save()
	return redirect('login:login')

login/templates/login/index.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">
	</head>
	<body>
		<div class="container">
			<nav class="vertical-nav bg-white" id="sidebar">
				 <div class="media d-flex align-items-center">
				 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
				 </div>
				<ul class="nav flex-column bg-white">
					<li class="nav-item">
						<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic bg-light">
            				Home
        				</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'login:login' %}" class="nav-link text-dark font-italic">
            				Login
        				</a>
					</li>
				</ul>
			</nav>
			
	    	<div class="page-content" id="content">
	    		<!-- <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button> -->
				<h1> Credit Risk Evaluation Application </h1>
				<div>
					<p>
						This application helps a loan granting officer of a
						bank or financial organisation to evaluate the loan applications.
						This helps in making decisions with regard to the applied loans.<br>
						<b>Background: </b>Risk for the applied loan can be evaluated using
						three methods - Rule based, Statistical based and Machine Learning based.
						Rule based models rely on well defined rules to judge a use case while
						Statistical and Machine Learning models rely on the data of other
						previously given loans. A decision can be suggested in this case by analysis
						of this data.<br> 
						<b>Usage of the application: </b>Points to note while using the application:
						<ol>
							<li>
								<b>Users: </b>There are two users of the application: Loan Administrator and
								Loan Officer. Loan Admin is responsible for setting rules for the rule
								based model and adding dataset for statistical and ML based models.
								Loan Officer can add the dataset for testing the loan applicants and
								choose to see the results for a loan id using any of the three models
								for evaluation.
							</li>
							<li>
								<b>Setting rules: </b> For rule based model, add features using the "Add 
								Feature" screen, configure the feature using "Configuration" screen
								with a weightage between 0 and 1 such that weightages of all the features 
								add to 1. Then, set criteria for a feature using "Criteria" screen.
							</li>
							<li>
								<b>Setting criteria: </b> 
								<ul>
									<li>
										Select the feature, product and category from the dropdown lists in the
										"Criteria" screen. 
									</li>
									<li>
										Select the data source. If it is XML/JSON, specify the source url in
										API and provide the key. If it is SQL,	write the SQL query from the
										database named "db". e.g. "SELECT loan_amnt from db". You need not
										provide key for SQL.
									</li>
									<li>
										Set criterias and their scores. If the feature is categorical, set
										criteria using "is feature_name". e.g. For a feature say "gender",
										set the score for criteria "is Male" and "is Female" differently.  
									</li>
								</ul>
							</li>
							<li>
								<b>Uploading datasets: </b>
								<ul>
									<li>
										For uploading dataset of customers who have applied for loan, just 
										uplaod a ".csv" file in the "Upload Dataset" screen of Loan Officer.
									</li>
									<li>
										For uploading dataset for training, upload a ".csv" file in "Upload 
										Dataset" screen of Loan Admin.
									</li>
								</ul>
							</li>
							<li>
								<b>Seeing Results: </b>
								<ul>
									<li>
										You can see the results by entering a loan id and 
										checking any of the models in the "Scorecard" screen of the Loan 
										Officer if	the screen shows that the model is ready for analysis.
									</li>
									<li>
										The rule based model gives the score (between 1-10) according to the
										specified rules.
									</li>
									<li>
										The statistical and machine learning based models give probability of
										approval of the loan according to the best machine learning/statistical
										model implemented.
									</li>
								</ul>
							</li>
						</ol>  
					</p>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<script>
			$(function() {
				// Sidebar toggle behavior
  				$('#sidebarCollapse').on('click', function() {
    				$('#sidebar, #content').toggleClass('active');
  				});
			});
		</script>
	</body>
</html>

login/templates/login/login.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<!-- Bootstrap tooltips -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
		<!-- Bootstrap core JavaScript -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
		<!-- MDB core JavaScript -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
		<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">
		<style>
			.card-header:first-child {
			    border-radius: calc(.25rem - 1px) calc(.25rem - 1px) 0 0;
			}
			.info-color {
    			background-color: #33b5e5 !important;
			}
			.white-text {
			    color: #fff !important;
			}
			.text-center {
			    text-align: center!important;
			}
			.pb-4, .py-4 {
			    padding-bottom: 1.5rem!important;
			}
			.pt-4, .py-4 {
			    padding-top: 1.5rem!important;
			}
			.card-header {
			    padding: .75rem 1.25rem;
			    margin-bottom: 0;
			    background-color: rgba(0,0,0,.03);
			    border-bottom: 1px solid rgba(0,0,0,.125);
			}
		</style>
	</head>
	<body>
		<div class="container">
			<nav class="vertical-nav bg-white" id="sidebar">
				 <div class="media d-flex align-items-center">
				 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
				 </div>
				<ul class="nav flex-column bg-white">
					<li class="nav-item">
						<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic">
		    				Home
						</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'login:login' %}" class="nav-link text-dark font-italic bg-light">
		    				Login
						</a>
					</li>
				</ul>
			</nav>
			<div class="page-content" id="content">
				<div class="card">
					<h5 class="card-header info-color white-text text-center py-4">
						Login
					</h5>
					{% if messages %}
					<div class="alert alert-danger" role="alert">
					    {% for message in messages %}
					    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					    {% endfor %}
					</div>
					{% endif %}
					<div class="card-body px-lg-5 pt-0">
						<br>
						<form class="" style="color: #757575;" action="{% url 'login:authenticate_and_redirect' %}" method="POST" role="form">
							{% csrf_token %}
							{{ form.name }}
							<br>
							<div class="md-form">
								{{ form.password.label }}
								{{ form.password }}
							</div>
							<br>
							<input type="submit" value="Submit" class="btn btn-primary" id="submit">
						</form>
					</div>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<script>
			$(function() {
				// Sidebar toggle behavior
  				$('#sidebarCollapse').on('click', function() {
    				$('#sidebar, #content').toggleClass('active');
  				});
			});
			// $(document).ready(function(){
			//     $("#submit").on('click', function () {
			// 		$.ajax({
			// 			url: '/login/ajax/save_user/',
			// 			dataType: 'json',
			// 			success: function (data) {
			// 				$("#alert").val("")
			// 			}
			// 		});
			//     });
			// });
		</script>
	</body>
</html>