credit_risk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('loan_admin/', include('loan_admin.urls')),
    path('loan_officer/', include('loan_officer.urls')),
    path('', include('login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loan_admin/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

app_name = 'loan_admin'
urlpatterns = [
	path('', views.index, name='index'),
	path('add', views.addFeature, name='add'),
	path('index/?add=ok1', views.index, name='index1'),
	path('configuration', views.configuration, name='configuration'),
	path('criteria', views.criteria, name='criteria'),
	path('weigh', views.addConfiguration, name='weigh'),
	path('addCriteria', views.addCriteria, name='cri'),
	path('configuration/?add1=ok2', views.configuration, name='configuration1'),
	path('criteria/?add2=ok3', views.criteria, name='criteria1'),
	path('uploadCSV', views.uploadCSV, name='uploadCSV'),
	path('uploadCSV/?add3=ok4', views.uploadCSV, name='uploadCSV1'),
	path('addApplicant', views.addApplicant, name='addApplicant'),
	path('set_scale', views.set_scale, name='set_scale'),
	path('set_scale/?add4=ok5', views.set_scale, name='setScale1'),
	path('set', views.addScale, name='set'),
	re_path(r'^ajax/get_feature_values/$', views.get_feature_values, name='get_feature_values'),
	re_path(r'^ajax/get_configuration_values/$', views.get_configuration_values, name='get_configuration_values'),
	re_path(r'^ajax/get_criteria_values/$', views.get_criteria_values, name='get_criteria_values'),
	re_path(r'^ajax/get_scale_values/$', views.get_scale_values, name='get_scale_values'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
import os

STATIC_ROOT = os.path.join(settings.BASE_DIR, "static/login")

app_name = 'login'
urlpatterns = [
	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('login?add=invalid', views.login, name='login1'),
	path('authenticate_and_redirect', views.authenticate_and_redirect, name='authenticate_and_redirect'),
	path('login/logout', views.logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loan_admin/models.py
from django.db import models
from django import forms
# Create your models here.

class UploadFile(models.Model):
	target = models.CharField(default="loan_status", max_length=100)
	columns = models.CharField(max_length=1000000)
	nominal_features = models.CharField(max_length=1000000)

class Feature(models.Model):
	VALUE_CHOICES = [
		('Bi', 'Binary'),
		('No', 'Nominal'),
		('In', 'Interval'),
		('Ra', 'Ratio'),

	]
	DATA_CHOICES = [
		('Nu', 'Numeric'),
		('Ch', 'Character'),
		('Da', 'Date'),
	]
	CATEGORY_CHOICES = [
		('In', 'Individual'),
		('Co', 'Company'),
		('Cy', 'Country'),
	]
	name = models.CharField(max_length=100)
	value = models.CharField(max_length=10, choices=VALUE_CHOICES)
	data_type = models.CharField(max_length=10, choices=DATA_CHOICES)
	category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
	status = models.BooleanField(default=False)

	def __str__(self):
		return self.name

class Configuration(models.Model):
	# FEATURE_CHOICES = [
	# 	('In', 'Individual'),
	# 	('Co', 'Company'),
	# 	('Cy', 'Country'),
	# ]
	CATEGORY_CHOICES = [
		('In', 'Individual'),
		('Co', 'Company'),
		('Cy', 'Country'),
	]
	PRODUCT_CHOICES = [
		('Ag', 'Agricultural'),
		('Ho', 'Home'),
		('Pe', 'Personal'),
		('Ve', 'Vehicle'),
	]
	feature = models.CharField(max_length=100, null=True)
	category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
	product = models.CharField(max_length=10, choices=PRODUCT_CHOICES)
	weightage = models.FloatField()

	def __str__(self):
		return self.feature

class Criteria(models.Model):
	feature = models.CharField(max_length=100, null=True)
	category = models.CharField(max_length=10)
	product = models.CharField(max_length=10)
	data_source = models.CharField(max_length=10)
	api = models.CharField(max_length=10000)
	key = models.CharField(max_length=100)

class CriteriaHelper(models.Model):
	criteria = models.ForeignKey(Criteria, 
		on_delete=models.CASCADE,)
	entry = models.CharField(max_length=1000000)
	score = models.IntegerField()

class SetScale(models.Model):
	red = models.IntegerField()
	green = models.IntegerField()

loan_admin/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from .models import Feature
from .models import Configuration
from .models import Criteria, CriteriaHelper, SetScale
from .forms import FeatureForm
from .forms import ConfigurationForm

from django.urls import reverse
from urllib.parse import urlencode
from .forms import UploadFileForm, CriteriaForm, SetScaleForm
import sys
from django.contrib import messages
from django.http import JsonResponse
from login.models import Sessions
# Create your views here.
def get_params(request, key):
	add = request.GET.get(key)
	session = Sessions.objects.all().first()
	return {'add':add, 'session':session.user}

def index(request):
	params = get_params(request, 'add')
	if(params['add'] == 'ok1'):
		messages.info(request, 'Record created successfully')
		alert = 'ok'
	elif(params['add'] == 'invalid1'):
		messages.info(request, 'Record already exists')
		alert = 'invalid1'
	else:
		alert = 'none'
	form = FeatureForm()
	context = {'form':form, 'session':params['session'], 'alert':alert}
	return render(request, 'loan_admin/index.html', context)

def configuration(request):
	params = get_params(request, 'add1')
	form = ConfigurationForm()
	if(params['add'] == 'ok2'):
		messages.info(request, 'Record created successfully')
	context = {'form':form, 'session':params['session']}
	return render(request, 'loan_admin/configuration.html', context)

def get_feature_values(request):
	name = request.GET.get('name')
	ins = Feature.objects.filter(name=name).first()
	data = {
		'value': ins.value,
		'data_type': ins.data_type,
		'category': ins.category,
		'status': ins.status
	}
	return JsonResponse(data)

@require_POST
def addFeature(request):
	form = FeatureForm(request.POST)
	url = reverse('loan_admin:index') 
	if form.is_valid():
		feature = form.save()
		base_url = reverse('loan_admin:index')
		query_string =  urlencode({'add': 'ok1'})
		url = '{}?{}'.format(base_url, query_string)
	else:
		base_url = reverse('loan_admin:index')
		query_string =  urlencode({'add': 'invalid1'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

@require_POST
def addConfiguration(request):
	form = ConfigurationForm(request.POST)
	url = reverse('loan_admin:configuration') 
	if form.is_valid():
		feature = form.save()
		base_url = reverse('loan_admin:configuration')
		query_string =  urlencode({'add1': 'ok2'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

def get_configuration_values(request):
	feature = request.GET.get('feature')
	ins = Configuration.objects.filter(feature=feature).first()
	data = {
		'product': ins.product,
		'weightage': ins.weightage,
		'category': ins.category
	}
	return JsonResponse(data)

def criteria(request):
	params = get_params(request, 'add2')
	form = CriteriaForm()
	if(params['add'] == 'ok3'):
		messages.info(request, 'Record created successfully')
	context = {'form':form, 'session':params['session']}
	return render(request, 'loan_admin/criteria.html', context)

@require_POST
def addCriteria(request):
	print("----------")
	print(request.POST.get('entry_2'))
	print("----------")
	form = CriteriaForm(request.POST)
	url = reverse('loan_admin:criteria') 
	print("++++")
	if form.is_valid():
		form.clean()
		print("?????")
		form.save()
		print("*****")
		base_url = reverse('loan_admin:criteria')
		query_string =  urlencode({'add2': 'ok3'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

def get_criteria_values(request):
	feature = request.GET.get('feature')
	category = request.GET.get('category')
	product = request.GET.get('product')
	ins = Criteria.objects.filter(feature=feature).filter(category=category).filter(product=product).first()
	crih_ins = CriteriaHelper.objects.filter(criteria=ins)
	entries, scores = get_criteria_values_helper(crih_ins)
	data = {
		'api': ins.api,
		'data_source': ins.data_source,
		'key': ins.key,
		'entries': entries,
		'scores': scores
	}
	return JsonResponse(data)

def get_criteria_values_helper(crih_ins):
	entries = ""
	scores = ""
	if(len(crih_ins) != 0):
		entries += crih_ins[0].entry
		scores += str(crih_ins[0].score)
		i = 0
		for instance in crih_ins:
			print(len(crih_ins))
			if(i == 0):
				i += 1
				continue
			entries += ','
			scores += ','
			entries += instance.entry
			scores += str(instance.score)
	return entries, scores

def set_scale(request):
	params = get_params(request, 'add4')
	form = SetScaleForm()
	if(params['add'] == 'ok5'):
		messages.info(request, 'Record created successfully')
	context = {'form':form, 'session':params['session']}
	return render(request, 'loan_admin/set_scale.html', context)

def addScale(request):
	form = SetScaleForm(request.POST)
	url = reverse('loan_admin:set_scale')
	if form.is_valid():
		form.save()
		base_url = reverse('loan_admin:set_scale')
		query_string =  urlencode({'add4': 'ok5'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

def get_scale_values(request):
	ins = SetScale.objects.all().first()
	data = {
		'red': ins.red,
		'green': ins.green,
	}
	return JsonResponse(data)

def uploadCSV(request):
	params = get_params(request, 'add3')
	form = UploadFileForm()
	session = Sessions.objects.all().first()
	if(params['add'] == 'ok4'):
		messages.info(request, 'Record created successfully')
	context = {'form':form, 'session':params['session']}
	return render(request, 'loan_admin/uploadCSV.html', context)

@require_POST
def addApplicant(request):
	form = UploadFileForm(request.POST, request.FILES)
	url = reverse('loan_admin:uploadCSV')
	print(form.errors)
	print(form.is_valid(), file=sys.stderr)
	if form.is_valid():
		form.process_data(request.POST, request.FILES['file'])
		base_url = reverse('loan_admin:uploadCSV')
		query_string =  urlencode({'add3': 'ok4'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

loan_admin/templates/loan_admin/configuration.html
{% load crispy_forms_tags %}
{% load static %}
{% if session == "1" %}
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
		    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
			<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
			<!-- Material Design Bootstrap -->
			<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet">
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
			<!-- Bootstrap tooltips -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
			<!-- Bootstrap core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
			<!-- MDB core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
			<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">

		</head>
		<body>
			<div class="container">
				<nav class="vertical-nav bg-white" id="sidebar">
					 <div class="media d-flex align-items-center">
					 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
					 </div>
					<ul class="nav flex-column bg-white">
						<li class="nav-item">
							<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic">
	            				Home
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:index' %}" class="nav-link text-dark font-italic">
	            				Add Feature
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:configuration' %}" class="nav-link text-dark font-italic bg-light">
	            				Configuration
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:criteria' %}" class="nav-link text-dark font-italic">
	            				Criteria
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:set_scale' %}" class="nav-link text-dark font-italic">
	            				Set Scale
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:uploadCSV' %}" class="nav-link text-dark font-italic">
	            				Upload Dataset
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'login:logout' %}" class="nav-link text-dark font-italic" id="link">
		        				Logout
		    				</a>
						</li>
					</ul>
				</nav>
				<div class="page-content" id="content">
					<div class="card">

					    <h5 class="card-header info-color white-text text-center py-4">
					        <strong>Configuration</strong>
					    </h5>
					    {% if messages %}
						<div class="alert alert-success" role="alert">
						    {% for message in messages %}
						    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
						    {% endfor %}
						</div>
						{% endif %}
					    <!--Card content-->
					    <div class="card-body px-lg-5 pt-0">
					    	
					        <!-- Form -->
					        <form class="" style="color: #757575;" action="{% url 'loan_admin:weigh' %}" method="POST" role="form">
					        	{% csrf_token %}
					            <!-- Subject -->
					            <br>
					            <div class="" id="id_1">
					            	<label>{{ form.feature.label }}</label>
					            	{{ form.feature }}

					            </div>
					            <div>
						           <label>{{ form.category.label }}</label>
					            	{{ form.category }}
					            </div>
					            <div>
						            <label>{{ form.product.label }}</label>
						            {{ form.product }}
						        </div>
					            <div class="md-form">
							        {{ form.weightage }}
							        <label id='1' for="1">{{ form.weightage.label }}</label>
							    </div>
					            <input type="button" class="btn btn-default" value="Get" id="get_value">
					            <!-- Send button -->
					            <input class="btn btn-primary" value="submit" type="submit">

					        </form>
					        <!-- Form -->

					    </div>
					<!-- <h1> Configuration </h1>
					{% if messages %}
					<div class="alert alert-success" role="alert">
					    {% for message in messages %}
					    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					    {% endfor %}
					</div>
					{% endif %}
					<form action="{% url 'loan_admin:weigh' %}" method="POST" role="form">
						{% csrf_token %}
						<b>{{ form.feature.label }}*</b>
						{{ form.feature }}<br><br>
						<div id="id_1">
							<b>{{ form.category.label }}*</b>
							{{ form.category }}<br><br>
						</div>
						<div id="id_2">
							<b>{{ form.product.label }}*</b>
							{{ form.product }}<br><br>
						</div>
						<b>{{ form.weightage.label }}*</b>
						{{ form.weightage }}
						<br>
						<input type="button" class="btn btn-success" value="Get" id="get_value">
					    <input type="submit" value="Submit" class="btn btn-primary">
					</form> -->
				</div>
			</div>
			<script>
				$(document).ready(function(){
				    $("#get_value").on('click', function () {
						var feature = $("#id_feature").val();
						console.log(feature);
						$.ajax({
							url: '/loan_admin/ajax/get_configuration_values/',
							data: {
								'feature': feature
							},
							dataType: 'json',
							success: function (data) {
								$('#1').val('')
								$("#id_weightage").val(data.weightage);
							}
						});
				    });
				    $('.mdb-select').materialSelect();
				});
			</script>
		</body>
	</html>
{% else %}
	Page not found.
{% endif %}

loan_admin/templates/loan_admin/criteria.html
{% load crispy_forms_tags %}
{% load static %}
{% if session == "1" %}
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
		    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
			<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
			<!-- Material Design Bootstrap -->
			<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet">
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
			<!-- Bootstrap tooltips -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
			<!-- Bootstrap core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
			<!-- MDB core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
			<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">
		</head>
		<body>
			<div class="container">
				<nav class="vertical-nav bg-white" id="sidebar">
					 <div class="media d-flex align-items-center">
					 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
					 </div>
					<ul class="nav flex-column bg-white">
						<li class="nav-item">
							<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic">
	            				Home
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:index' %}" class="nav-link text-dark font-italic">
	            				Add Feature
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:configuration' %}" class="nav-link text-dark font-italic">
	            				Configuration
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:criteria' %}" class="nav-link text-dark font-italic bg-light">
	            				Criteria
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:set_scale' %}" class="nav-link text-dark font-italic">
	            				Set Scale
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_admin:uploadCSV' %}" class="nav-link text-dark font-italic">
	            				Upload Dataset
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'login:logout' %}" class="nav-link text-dark font-italic" id="link">
		        				Logout
		    				</a>
						</li>
					</ul>
				</nav>
				<div class="page-content" id="content">
					<div class="card">

					    <h5 class="card-header info-color white-text text-center py-4">
					        <strong>Criteria</strong>
					    </h5>
					    {% if messages %}
						<div class="alert alert-success" role="alert">
						    {% for message in messages %}
						    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
						    {% endfor %}
						</div>
						{% endif %}
					    <!--Card content-->
					    <div class="card-body px-lg-5 pt-0">
					    	
					        <!-- Form -->
					        <form class="" style="color: #757575;" action="{% url 'loan_admin:cri' %}" method="POST" role="form">
					        	{% csrf_token %}
					            <!-- Subject -->
					            <br>
					            <div class="" id="id_1">
					            	<label>{{ form.feature.label }}</label>
					            	{{ form.feature }}

					            </div>
					            <div>
						           <label>{{ form.category.label }}</label>
					            	{{ form.category }}
					            </div>
					            <div>
						            <label>{{ form.product.label }}</label>
						            {{ form.product }}
						        </div>
					            <label>Data Source*: &nbsp &nbsp</label>
								{% for radio in form.data_source %}
								    <label class="radio-inline" for="{{ radio.id_for_label }}">
								        <span class="radio">{{ radio.tag }}</span>
								        {{ radio.choice_label }}
								    </label>
								{% endfor %}
								<div class="md-form">
									<label>{{ form.api.label }}</label>
									{{ form.api }}
								</div>
								<div class="md-form">
									<label>{{ form.key.label }}</label>
									{{ form.key }}
								</div>
								<table>
									<tr id="new_row">
										<td>
											<div class="md-form">
												<label>{{ form.entry_1.label }}</label>
												{{ form.entry_1 }}
											</div>
										</td>
										<td>
											<div class="md-form">
												<label>{{ form.score_1.label }}</label>
												{{ form.score_1 }}
											</div>
										</td>
									</tr>
								</table>
								<input type="button" class="new btn-light btn-sm" value="Add Row"><br>
					            <input type="button" class="btn btn-default" value="Get" id="get_value">
					            <!-- Send button -->
					            <input class="btn btn-primary" value="submit" type="submit">

					        </form>
					        <!-- Form -->

					    </div>
					<!-- <h1> Criteria </h1>
					<br>
					{% if messages %}
					<div class="alert alert-success" role="alert">
					    {% for message in messages %}
					    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					    {% endfor %}
					</div>
					{% endif %}
					<form action="{% url 'loan_admin:cri' %}" method="POST" role="form" class=".interest-list-new">
						{% csrf_token %}
						<b>{{ form.feature.label }}</b>
						{{ form.feature }}
						<br><br>
						<b>{{ form.category.label }}</b>
						{{ form.category }}
						<br><br>
						<b>{{ form.product.label }}</b>
						{{ form.product }}
						<br><br>
						<b><label>Data Source*: &nbsp &nbsp</label></b>
						{% for radio in form.data_source %}
						    <label class="radio-inline" for="{{ radio.id_for_label }}">
						        <span class="radio">{{ radio.tag }}</span>
						        {{ radio.choice_label }}
						    </label>
						{% endfor %}
						<br><br>
						<b>{{ form.api.label }}</b>
						{{ form.api }}
						<br>
						<b>{{ form.key.label }}</b>
						{{ form.key }}
						<br>
						<table>
							<tr id="new_row">
								<td>
									<b>{{ form.entry_1.label }}</b>
									{{ form.entry_1 }}
								</td>
								<td>
									<b>{{ form.score_1.label }}</b>
									{{ form.score_1 }}
								</td>
							</tr>
						</table>
						<input type="button" class="new btn-default btn-sm" value="Add Row">
						<br><br>
						<input type="button" class="btn btn-success" value="Get" id="get_value">
					    <input type="submit" value="Submit" class="btn btn-primary">
					</form> -->
				</div>
			</div>
			<script>
				$(document).ready(function(){
					$('.new').on('click', function() {
		                let $this = $(document.getElementById('new_entry'))
		                let $th = $(document.getElementById('new_score'))
		                let name = $this.attr('name')
					    let name1 = $th.attr('name')
		                let n = parseInt(name.split('_')[1]) + 1
					    let n1 = parseInt(name1.split('_')[1]) + 1
		                name = 'entry_' + n
					    name1 = 'score_' + n1
		                $("<tr id='new_row'><td><b><label>Criteria "+n+"</label></b>"+
		                "<input name='"+name+"' id='new_entry' class='form-control'></td><td><b><label>Score "+n1+"</label></b>"+
		                "<input name='"+name1+"' id='new_score' class='textinput textInput form-control'></td></tr>").insertAfter("#new_row")
		                $this.off('input', arguments.callee)
					    $this.removeAttr('id')
					    $th.removeAttr('id')
					    $("#new_row").removeAttr('id')
					});

				    $("#get_value").on('click', function () {
						var feature = $("#id_feature").val();
						var category = $("#id_category").val();
						var product = $("#id_product").val();
						$.ajax({
							url: '/loan_admin/ajax/get_criteria_values/',
							data: {
								'feature': feature,
								'category': category,
								'product': product
							},
							dataType: 'json',
							success: function (data) {
								console.log(data.data_source.toString())
								$("#id_data_source_" + parseInt(data.data_source-1).toString()).attr('checked', true);
								$("#id_api").val(data.api);
								$("#id_key").val(data.key);
								console.log(data.entries);
								if(data.entries != ""){
									var entry_arr = data.entries.split(',');
									var score_arr = data.scores.split(',');
									$("#new_entry").val(entry_arr[0]);
									$("#new_score").val(score_arr[0]);
									$("#new_entry").attr("name", "entry_1")
									$("#new_score").attr("name", "score_1")
									entry_arr.shift()
									score_arr.shift()
									var i;
									for(i=0;i<entry_arr.length-1;i++){
										console.log(entry_arr[i]);
										let n = i + 2;
										let n1 = n;
						                let name = 'entry_' + n
									    let name1 = 'score_' + n1
						                $("<tr id='new_row'><td><b><label>Criteria "+n+"</label></b>"+
						                "<input name='"+name+"' id='entry' class='form-control' value='"+entry_arr[i]+"'></td><td><b><label>Score "+n1+"</label></b>"+
						                "<input name='"+name1+"' id='score' class='textinput textInput form-control' value='"+score_arr[i]+"'></td></tr>").insertAfter("#new_row");
						                $("#new_row").removeAttr('id');               
									}
									console.log(entry_arr);
									let n = i + 2;
									let n1 = n;
					                let name = 'entry_' + n;
								    let name1 = 'score_' + n1;
									$("<tr id='new_row'><td><b><label>Criteria "+n+"</label></b>"+
						                "<input name='"+name+"' id='new_entry' class='form-control' value='"+entry_arr[i]+"'></td><td><b><label>Score "+n1+"</label></b>"+
						                "<input name='"+name1+"' id='new_score' class='textinput textInput form-control' value='"+score_arr[i]+"'></td></tr>").insertAfter("#new_row");
								}
							}

						});
					});
				});
			</script>
		</body>
	</html>
{% else %}
	Page not found.
{% endif %}