credit_risk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('loan_admin/', include('loan_admin.urls')),
    path('loan_officer/', include('loan_officer.urls')),
    path('', include('login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loan_officer/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'loan_officer'
urlpatterns = [
	path('', views.index, name='index'),
	path('uploadCSV', views.uploadCSV, name='uploadCSV'),
	path('result', views.result, name='result'),
	path('add', views.addApplicant, name='add'),
	path('uploadCSV/?add=ok', views.uploadCSV, name='uploadCSV'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
import os

STATIC_ROOT = os.path.join(settings.BASE_DIR, "static/login")

app_name = 'login'
urlpatterns = [
	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('login?add=invalid', views.login, name='login1'),
	path('authenticate_and_redirect', views.authenticate_and_redirect, name='authenticate_and_redirect'),
	path('login/logout', views.logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loan_officer/models.py
from django.db import models

class SavedState(models.Model):
	stat = models.CharField(max_length=10)
	ml = models.CharField(max_length=10)
	statandml = models.CharField(max_length=10, default="false")

loan_officer/forms.py
import csv
import io
from django import forms
from django.forms import ModelForm
from django.db import connection
from django.db import models
import sys

class FileUploadForm(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={'class': 'custom-file-input', 
        'id': "customFile", 'name': 'filename'}))
	
    def process_data(self, f):
        with open('media/credit_risk/dataset/test_id_dataset.csv', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
            destination.close()

class MyForm(forms.Form):
    loan_id = forms.CharField(max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    rule_based = forms.BooleanField(required=False,
        widget=forms.CheckboxInput(attrs={'class': 'custom-control-input', 'id': "customCheck1"}))
    statistical_based = forms.BooleanField(required=False,
        widget=forms.CheckboxInput(attrs={'class': 'custom-control-input', 'id': "customCheck2"}))
    ML_based = forms.BooleanField(required=False,
        widget=forms.CheckboxInput(attrs={'class': 'custom-control-input', 'id': "customCheck3"}))

loan_officer/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db import models
from django.views.generic import FormView
from django.urls import reverse
from urllib.parse import urlencode
from .forms import MyForm, FileUploadForm
from .predict import *
from .models import SavedState
from login.models import Sessions
# from notifications import notify

def get_params(request, keys=[]):
	ans = {}
	for key in keys:
		ans[key] = request.GET.get(key)
	ans['session'] = Sessions.objects.all().first().user
	ans['savedstate'] = SavedState.objects.all().first()
	return ans

def index(request):
	form = MyForm()
	params = get_params(request)
	status_bg = False
	if(params['savedstate'] is not None):
		status_bg = (params['savedstate'].stat == "true")
	context = {'form':form, 'status_bg':status_bg, 'session': params['session']}
	return render(request, 'loan_officer/index.html', context)

def result(request):
	params = get_params(request, ['loan_id', 'rule_based', 'statistical_based', 'ML_based'])
	if(params['savedstate'] == None):
		m = SavedState(stat="false", ml="false")
		m.save()
	if((params['statistical_based'] or params['ML_based']) and params['savedstate'].stat == "false"):
		return render(request, 'loan_officer/result.html', {'not_ready':True})
	ans = get_results(params['rule_based'], params['statistical_based'], params['ML_based'], params['loan_id'])
	arr = []
	arr.append(ans[0])
	arr += result_helper(ans)
	arr.append(ans[3])
	context = {'result': arr, 'session':params['session']}
	return render(request, 'loan_officer/result.html', context)

def result_helper(ans):
	arr = [None, None, None, None]
	if(ans[1]):
		arr[0] = ans[1].split(',')[0]
		arr[1] = ans[1].split(',')[1]
	if(ans[2]):
		arr[2] = ans[2].split(',')[0]
		arr[3] = ans[2].split(',')[1]
	return arr

def get_results(rule, stat, ml, loan_id):
	ans = [None, None, None, None]
	if(rule):			
		classifier = RuleClassifier()
		ans[0] = classifier.get_result(loan_id)
	if(stat):
		classifier = StatisticalClassifier()
		ans[1] = classifier.get_result(loan_id)
	if(ml):
		classifier = MLClassifier()
		ans[2] = classifier.get_result(loan_id)
	if(stat and ml):
		ans[3] = (SavedState.objects.all().first().statandml == 'stat')
	return ans

def uploadCSV(request):
	params = get_params(request, ['add'])
	form = FileUploadForm()
	if(params['add'] == 'ok'):
		messages.info(request, 'Record created successfully')
	context = {'form':form, 'session': params['session']}
	return render(request, 'loan_officer/uploadCSV.html', context)

@require_POST
def addApplicant(request):
	form = FileUploadForm(request.POST, request.FILES)
	url = reverse('loan_officer:uploadCSV')
	if form.is_valid():
		form.process_data(request.FILES['file'])
		base_url = reverse('loan_officer:uploadCSV')
		query_string =  urlencode({'add': 'ok'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

loan_officer/templates/loan_officer/index.html
{% load crispy_forms_tags %}
{% load static %}
{% if session == "2" %}
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
		    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
			<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
			<!-- Material Design Bootstrap -->
			<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet">
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
			<!-- Bootstrap tooltips -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
			<!-- Bootstrap core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
			<!-- MDB core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
			<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">
		</head>
		<body>
			<div class="container">
				<nav class="vertical-nav bg-white" id="sidebar">
					 <div class="media d-flex align-items-center">
					 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
					 </div>
					<ul class="nav flex-column bg-white">
						<li class="nav-item">
							<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic">
	            				Home
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_officer:index' %}" class="nav-link text-dark font-italic bg-light">
	            				Scorecard
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_officer:uploadCSV' %}" class="nav-link text-dark font-italic">
	            				Upload Dataset
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'login:logout' %}" class="nav-link text-dark font-italic" id="link">
	            				Logout
	        				</a>
						</li>
					</ul>
				</nav>
				<div class="page-content" id="content">
					<div class="card">
						<h5 class="card-header info-color white-text text-center py-4">
							Scorecard
						</h5>
						<div class="card-body px-lg-5 pt-0">
							<ul>
								<li>Rule - ready</li>
								<li>Stat and ML - {% if status_bg %}ready{% else %}not ready{% endif %} </li>
							</ul>
							<form style="color: #757575;" action="{% url 'loan_officer:result' %}" method="GET" role="form">
							    <div class="md-form">
							    	<label>Loan ID</label>
							    	{{ form.loan_id }}
							    </div>
							    <br>
							    <div class="custom-control custom-checkbox mb-3">
							    	{{ form.rule_based }}
							    	<label class="custom-control-label" for="customCheck1">Rule Based</label>
							    </div><div class="custom-control custom-checkbox mb-3">
							    	{{ form.statistical_based }}
							    	<label class="custom-control-label" for="customCheck2">Statistical Based</label>
							    </div>
							    <div class="custom-control custom-checkbox mb-3">
							    	{{ form.ML_based }}
							    	<label class="custom-control-label" for="customCheck3">ML Based</label>
							    </div>
							    <input type="submit" value="Submit" class="btn btn-primary">
							</form>
						</div>
					</div>
				</div>
			</div>
			<script>
				$(document).ready(function(){
					$("#link").on('click', function () {
						console.log("a");
					});
				});
			</script>
		</body>
	</html>
{% else %}
	Page not found.
{% endif %}

loan_officer/templates/loan_officer/result.html
{% load crispy_forms_tags %}
{% load static %}
{% if session == "2" %}
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
		    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
			<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">
		</head>
		<body>
			<div class="container">
				<nav class="vertical-nav bg-white" id="sidebar">
					 <div class="media d-flex align-items-center">
					 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
					 </div>
					<ul class="nav flex-column bg-white">
						<li class="nav-item">
							<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic">
	            				Home
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_officer:index' %}" class="nav-link text-dark font-italic">
	            				Scorecard
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_officer:uploadCSV' %}" class="nav-link text-dark font-italic">
	            				Upload Dataset
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'login:logout' %}" class="nav-link text-dark font-italic" id="link">
	            				Logout
	        				</a>
						</li>
					</ul>
				</nav>
				<div class="page-content" id="content">
					<h1> Results </h1>
				<div class="jumbotron">
					<div class="table-responsive">
						<table class="table table-bordered">
							<tbody>				
								{% if not_ready %}
									<tr><td>Model(s) is/are not ready.</td></tr>
								{% endif %}
								{% if result.0 %}
									<tr><td>Rule Based</td><td><b>Score: </b></td><td>{{ result.0 }}</td></tr>
								{% endif %}
								{% if result.1 %}				
								<tr><td rowspan="2">Statistical Based</td><td><b>Approve</b>&nbsp &nbsp</td><td>{{ result.1 }}</td></tr>
								<tr><td><b>Not Approve</b>&nbsp &nbsp</td><td>{{ result.2 }}</td></tr>
								{% endif %}
								{% if result.3 %}
								<tr><td rowspan="2">ML Based</td><td><b>Approve</b>&nbsp &nbsp</td><td>{{ result.3 }}</td></tr>
								<tr><td><b>Not Approve</b>&nbsp &nbsp</td><td>{{ result.4 }}</td></tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					<br>
					{% if result.5 %}
						Statistical model wins in performance measure.
					{% else %}
						ML model wins in performance measure.
					{% endif %}
				</div>		
			<script>		
				$(".custom-file-input").on("change", function() {
				  var fileName = $(this).val().split("\\").pop();
				  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
				});
			</script>
		</body>
	</html>
{% else %}
	Page not found.
{% endif %}

loan_officer/templates/loan_officer/uploadCSV.html
{% load crispy_forms_tags %}
{% load static %}
{% if session == "2" %}
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
		    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
			<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
			<!-- Material Design Bootstrap -->
			<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet">
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
			<!-- Bootstrap tooltips -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
			<!-- Bootstrap core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
			<!-- MDB core JavaScript -->
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
			<link rel="stylesheet" href="/media/credit_risk/static/css/navbar.css">
		</head>
		<body>
			<div class="container">
				<nav class="vertical-nav bg-white" id="sidebar">
					 <div class="media d-flex align-items-center">
					 	<img src="/media/credit_risk/logo.jpg" alt="..." class="">
					 </div>
					<ul class="nav flex-column bg-white">
						<li class="nav-item">
							<a href="{% url 'login:index' %}" class="nav-link text-dark font-italic">
	            				Home
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_officer:index' %}" class="nav-link text-dark font-italic">
	            				Scorecard
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'loan_officer:uploadCSV' %}" class="nav-link text-dark font-italic bg-light">
	            				Upload Dataset
	        				</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'login:logout' %}" class="nav-link text-dark font-italic" id="link">
	            				Logout
	        				</a>
						</li>
					</ul>
				</nav>
				<div class="page-content" id="content">
					<div class="card">
						<h5 class="card-header info-color white-text text-center py-4">
							Customer Dataset Upload
						</h5>
						{% if messages %}
						<div class="alert alert-success" role="alert">
						    {% for message in messages %}
						    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
						    {% endfor %}
						</div>
						{% endif %}
						<form style="color: #757575;" action="{% url 'loan_officer:add' %}" method="POST" enctype= multipart/form-data>
							{% csrf_token %}
							<br>
							<div class="custom-file">
								{{ form.file }}
								<label class="custom-file-label" for="customFile">Choose file</label>
							</div><br><br>
						    <input type="submit" value="Submit" class="btn btn-primary">
						</form>
					</div>
				</div>
			</div>
			<script>		
				$(".custom-file-input").on("change", function() {
				  var fileName = $(this).val().split("\\").pop();
				  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
				});
			</script>
		</body>
	</html>
{% else %}
	Page not found.
{% endif %}